### ISSUE TITLE
Overleaf Template Gallery

### ISSUE THREAD

**Issue by jpfairbanks** [Compositionality/compositionality-latex-template#15]
It might be helpful to have an official overleaf template for Compositionality Journal. The instructions for how to load it are [here](https://www.overleaf.com/learn/how-to/Can_I_create_my_own_LaTeX_templates%3F). Is that something that the editors would support?

**Comment by Jademaster** [comment]
Hi James, great idea. The overleaf template is now available [here](https://www.overleaf.com/latex/templates/compositionality-latex-template/cdyvqrvtzfwf).
